spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://Jayendra:<Jay@12345>@cluster0.aicxrfv.mongodb.net/?appName=Cluster0

jwt.secret=8f3d92c7a1b4e5f6d8a9c0b2e4f7a1d3c5e7f9b2a4d6c8e0f1a3b5d7e9c1f2a4

server.port=8080